In [1]:
import pandas as pd

df = pd.read_csv("Hwy26Crashes2019_S23.csv")
df

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Serial #,Crash Month,Crash Day,...,Participant Cause 2 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code,BAC Test Results Code,Alcohol Use Reported,Drug Use Reported,Participant Marijuana Use Reported,Participant Striker Flag
0,1809119,1,NaN,NaN,NaN,NaN,NaN,99992.0,3.0,14.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1809119,2,3409578.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN
3,1809119,2,3409579.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,9.0,9.0,0.0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2734,1860771,1,NaN,NaN,NaN,NaN,NaN,1465.0,5.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2735,1860771,2,3503992.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN
2737,1860771,2,3503993.0,NaN,NaN,2.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN

In [2]:
# crash_df = df[df['Record Type'] == 1]
# crash_df
crash_df = df[df["Record Type"] == 1].dropna(axis="columns", how="all")
crash_df

,Crash ID,Record Type,Serial #,Crash Month,Crash Day,Crash Year,Week Day Code,Crash Hour,County Code,City Section ID,...,Total Pedestrian Count,Total Pedestrian Fatality Count,Total Pedestrian Non-Fatal Injury Count,Total Pedalcyclist Count,Total Pedalcyclist Fatality Count,Total Pedalcyclist Non-Fatal Injury Count,Total Unknown Non-Motorist Count,Total Unknown Non-Motorist Fatality Count,Total Unknown Non-Motorist Injury Count,Total Vehicle Occupant Count
0,1809119,1,99992.0,3.0,14.0,2019.0,5.0,14.0,26.0,0.0,...,0.0,0.0,0.0,0.0,0.0,3.0,3.0,2.0,0.0,1.0
5,1809229,1,2405.0,3.0,3.0,2019.0,1.0,2.0,3.0,185.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0
9,1809637,1,1811.0,5.0,17.0,2019.0,6.0,99.0,3.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0
12,1810874,1,99981.0,4.0,7.0,2019.0,1.0,0.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0
16,1812266,1,5970.0,7.0,8.0,2019.0,2.0,14.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,5.0,5.0,2.0,0.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2716,1860371,1,3344.0,4.0,19.0,2019.0,6.0,20.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
2719,1860417,1,3385.0,4.0,20.0,2019.0,7.0,15.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,4.0,0.0,0.0
2724,1860427,1,3396.0,4.0,13.0,2019.0,7.0,21.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,4.0,4.0,3.0,0.0,1.0
2729,1860453,1,3423.0,4.0,22.0,2019.0,2.0,12.0,26.0,245.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,0.0,0.0
2734,1860771,1,1465.0,5.0,6.0,2019.0,2.0,15.0,3.0,185.0,...,0.0,0.0,0.0,0.0,0.0,2.0,2.0,1.0,0.0,1.0

In [3]:
# vehicle_df = df[df['Record Type'] == 2]
# vehicle_df
vehicle_df = df[df["Record Type"] == 2].dropna(axis="columns", how="all")
vehicle_df

,Crash ID,Record Type,Vehicle ID,Vehicle Coded Seq#,Total Count of Persons Involved,Total Persons Using Safety Equipment,Total Persons Not Using Safety Equipment,Total Persons Safety Equipment Use Unknown,Vehicle Ownership Code,Vehicle Special Use Code,...,Vehicle Action Code,Vehicle Cause 1 Code,Vehicle Cause 2 Code,Vehicle Cause 3 Code,Vehicle Event 1 Code,Vehicle Event 2 Code,Vehicle Event 3 Code,Vehicle Exceeded Posted Speed Flag,Vehicle Hit & Run Flag,Safety Equipment Used Quantity
1,1809119,2,3409578.0,1.0,1.0,0.0,9.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
3,1809119,2,3409579.0,2.0,1.0,0.0,1.0,0.0,0.0,3.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,1.0,2.0,0.0
6,1809229,2,3409765.0,1.0,1.0,0.0,4.0,0.0,1.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
10,1809637,2,3410470.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,62.0,10.0,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
13,1810874,2,3412622.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2727,1860427,2,3503379.0,2.0,0.0,0.0,1.0,0.0,9.0,6.0,...,NaN,NaN,NaN,0.0,0.0,3.0,0.0,0.0,3.0,0.0
2730,1860453,2,3503423.0,1.0,0.0,0.0,1.0,0.0,9.0,1.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
2732,1860453,2,3503424.0,2.0,0.0,0.0,1.0,0.0,9.0,6.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,0.0
2735,1860771,2,3503992.0,1.0,0.0,0.0,1.0,0.0,9.0,3.0,...,NaN,NaN,NaN,0.0,0.0,1.0,0.0,0.0,1.0,1.0
2737,1860771,2,3503993.0,2.0,0.0,0.0,1.0,0.0,9.0,1.0,...,NaN,NaN,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0

In [4]:
# particp_df = df[df['Record Type'] == 3]
# particp_df
particp_df = df[df["Record Type"] == 3].dropna(axis="columns", how="all")
particp_df

,Crash ID,Record Type,Vehicle ID,Participant ID,Participant Display Seq#,Vehicle Coded Seq#,Participant Vehicle Seq#,Safety Equipment Un-used Quantity,Safety Equipment Use Unknown Quantity,Vehicle Occupant Count,...,Non-Motorist Travel Direction To,Non-Motorist Location,Participant Action,Participant Error 1 Code,Participant Error 2 Code,Participant Error 3 Code,Participant Cause 3 Code,Participant Event 1 Code,Participant Event 2 Code,Participant Event 3 Code
2,1809119,3,3409578.0,3887884.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
4,1809119,3,3409579.0,3887885.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,9.0,9.0,0.0
7,1809229,3,3409765.0,3888073.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
8,1809229,3,0.0,3888074.0,2.0,NaN,1.0,3.0,0.0,0.0,...,NaN,NaN,18.0,NaN,NaN,NaN,0.0,9.0,1.0,0.0
11,1809637,3,3410470.0,3888766.0,1.0,1.0,1.0,1.0,0.0,0.0,...,81.0,NaN,1.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2728,1860427,3,3503379.0,3990896.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0.0
2731,1860453,3,3503423.0,3990937.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2733,1860453,3,3503424.0,3990938.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2736,1860771,3,3503992.0,3991482.0,1.0,1.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2738,1860771,3,3503993.0,3991483.0,2.0,2.0,1.0,1.0,0.0,0.0,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [5]:
# Every crash has a unique crash ID
msg = "Existence assertion: Every crash has a unique crash ID"
for index, row in df.iterrows():
    if row["Record Type"] in ["1", "2", "3"]:
        assert df["Crash ID"].nunique == len(df), print(f"{msg} FAILED")
print(f"{msg} SUCCEEDED")

Existence assertion: Every crash has a unique crash ID SUCCEEDED

In [6]:
# Every crash should have a vehicle ID
msg = "Existence assertion: Every crash should have a vehicle ID"
new_df = set(df["Vehicle ID"])
if df["Record Type"].any == 2:
    assert len(new_df) == len(vehicle_df), print(f"{msg} FAILED")
else:
    print(f"{msg} SUCCEEDED")

Existence assertion: Every crash should have a vehicle ID SUCCEEDED

In [7]:
# Every crash county is in Oregon
msg = "Limit assertion: Every crash county is in Oregon"
if not (df["County Code"] >= 1).all() & (df["County Code"] <= 36).all():
    print(f"{msg} SUCCEEDED")
else:
    print(f"{msg} FAILED")

Limit assertion: Every crash county is in Oregon SUCCEEDED

In [8]:
# Every crash occurred during 2019
msg = "Limit assertion: Every crash occurred during 2019"
df_year = df["Crash Year"] == 2019
for year in df_year:
    if not year == "2019":
        print(f"{msg} SUCCEEDED")
        break
    else:
        print(f"{msg} FAILED")
        break

Limit assertion: Every crash occurred during 2019 SUCCEEDED

In [9]:
# Every crash has a crash date
msg = "Intra-record assertion: Every crash has a crash date"
for index, row in df.iterrows():
    if row["Record Type"] == 1:
        if pd.isna(row["Crash Day"]) or row["Crash Day"] == "":
            raise AssertionError("All Crashes do not have a date")
print(f"{msg} SUCCEEDED")

Intra-record assertion: Every crash has a crash date SUCCEEDED

In [10]:
# Every person involved in a crash has an ID
msg = "Intra-record assertion: Every person involved in a crash has an ID"
assert (particp_df["Participant ID"]).all(), print(f"{msg} FAILED")
print(f"{msg} SUCCEEDED")

Intra-record assertion: Every person involved in a crash has an ID SUCCEEDED

In [11]:
# Each crash with a latitude must have a longitude
msg = "Intra-record assertion: Each crash with a latitude must have a longitude"
for row in range(len(crash_df)):
    if pd.isnull(crash_df.loc[row, "Latitude Degrees"]) and not pd.isnull(
        crash_df.loc[row, "Longitude Degrees"]
    ):
        raise AssertionError("Each crash with a latitude do not have a longitude")
    else:
        print(f"{msg} SUCCEEDED")
        break

Intra-record assertion: Each crash with a latitude must have a longitude SUCCEEDED

In [12]:
# Each crash has atleast one vehicle involved
msg = "Inter-record assertion: Each Crash has atleast one vehicle"
assert not (df["Participant Vehicle Seq#"]).all() == 0, print(f"{msg} FAILED")

print(f"{msg} SUCCEEDED")

Inter-record assertion: Each Crash has atleast one vehicle SUCCEEDED

In [13]:
# Each participant listed in the crash data was a part of known crash
msg = "Inter-record assertion: Each participant listed in the crash data was a part of known crash"
list1 = set(df["Participant ID"])
for index, rows in particp_df.iterrows():
    if rows["Participant ID"] in list1:
        print(f"{msg} SUCCEEDED")
        break
    else:
        print(f"{msg} FAILED")

Inter-record assertion: Each participant listed in the crash data was a part of known crash SUCCEEDED

In [14]:
# Every vehicle listed in the crash data was part of a known crash
msg = "Inter-record assertion: Every vehicle listed in the crash data was part of a known crash"
list2 = df["Vehicle ID"].unique()
for index, row in vehicle_df.iterrows():
    if row["Vehicle ID"] not in list2:
        raise AssertionError(
            "Not every vehicle listed in the crash data was part of a known crash"
        )
print(f"{msg} SUCCEEDED")

Inter-record assertion: Every vehicle listed in the crash data was part of a known crash SUCCEEDED

In [15]:
# The majority of crashes in the data involve vehicles used to transport students

# vehicle_df.columns.tolist()
msg = "Summary assertion: The majority of crashes in the data involve vehicles used to transport students"

vehicle_type_count = df["Vehicle Type Code"].value_counts().idxmax()
print(f"Most crashes recorded has the vehicle type code: {vehicle_type_count}")
if vehicle_type_count:
    print(f"{msg} SUCCEEDED")
else:
    print(f"{msg} FAILED")
# print(vehicle_type_count)

Most crashes recorded has the vehicle type code: 7.0
Summary assertion: The majority of crashes in the data involve vehicles used to transport students SUCCEEDED

In [16]:
# There were thousands of crashes but not millions
msg = "Summary assertion: There were thousands of crashes but not millions"
new_list = set(df[list])
num_crashes = len(new_list)
if num_crashes > 1000000 and num_crashes < 1000:
    raise AssertionError("Number of crashes are not reported in thousands")
else:
    print(f"{msg} SUCCEEDED")

Summary assertion: There were thousands of crashes but not millions SUCCEEDED

In [17]:
# Every crash happened in Highway 26
msg = "Summary assertion: Every crash happened in Highway 26"
assert not crash_df["Highway Number"].all() == 26, print(f"{msg} FAILED")
print(f"{msg} SUCCEEDED")

Summary assertion: Every crash happened in Highway 26 SUCCEEDED

In [18]:
# Crashes frequently happen during afternoon(middle of the day)
msg = "Statistical distribution assertion: Crashes frequently happen during afternoon(middle of the day)"

peak_hour = df["Crash Hour"].value_counts().idxmax()
print(f"Peak Hour: {peak_hour}")

if peak_hour:
    print(f"{msg} SUCCEEDED")
else:
    raise AssertionError("Crashes are not frequently during afternoon")

Peak Hour: 15.0
Statistical distribution assertion: Crashes frequently happen during afternoon(middle of the day) SUCCEEDED

In [19]:
# Crash Data is evenly distributed throughout the year
msg = "Statistical distribution assertion: Crash Data is evenly distributed throughout the year"

crashes_per_month = crash_df["Crash Month"].value_counts()
print(crashes_per_month)

crashes_range = crashes_per_month.max() - crashes_per_month.min()
threshold = 10
if crashes_range <= threshold:
    print(f"{msg} SUCCEEDED")
else:
    raise AssertionError(f"{msg} FAILED")

3.0     57
1.0     56
4.0     53
2.0     46
12.0    44
5.0     41
7.0     37
10.0    36
6.0     36
11.0    35
9.0     34
8.0     33
Name: Crash Month, dtype: int64

AssertionError: Statistical distribution assertion: Crash Data is evenly distributed throughout the year FAILED

In [21]:
crash_df.to_csv("crashdata_1.csv", index=False)
vehicle_df.to_csv("vehicledata_2.csv", index=False)
particp_df.to_csv("participantdata_3.csv", index=False)